### ISSUE TITLE
deliver function returns a #Reference in body

### ISSUE THREAD

**Issue by john-griffin** [pablo-co/bamboo_postmark#13]
After the timeout/config update was released it is no longer possible to perform any operations the body contents received from the deliver function. Instead of getting a regular string inside body it includes a `#Reference`. I believe this is because the `with_body` is no longer passed to hackney. https://github.com/benoitc/hackney/blame/master/README.md#L174

**Comment by pablo-co** [comment]
Thanks for reporting this @john-griffin! #14 fixes this issue, just released version 0.4.1 with this fix.

**Comment by john-griffin** [comment]
Thanks again @pablo-co 😃
