### ISSUE TITLE
put_params to put_params

### ISSUE THREAD

**Issue by guidoholz** [pablo-co/bamboo_postmark#15]
Hi

in your example of additional parameters  you should change put_paramS to put_param.

Another interesting point is, how you can add attachments with put_param

e.g. could be:
```elixir
email
|> Bamboo.PostmarkHelper.put_param("Attachments",
   [
     %{
       Name: file.txt,
       Content: "/some/file.txt" |> File.read!() |> Base.encode64(),
       ContentType: "txt"
     }
   ])
```

it took a bit to figure out :)

thanks for the package!

**Comment by pablo-co** [comment]
Thanks for pointing out the typo. Your file example is definitely something not trivial to figure out, I'll make sure to add it to the README. Thank you!
