### ISSUE TITLE
deliver/2 shouldn't throw exceptions

### ISSUE THREAD

**Issue by chingan-tsc** [pablo-co/bamboo_postmark#20]
Hi, this may sound opinionated but IMHO I think the return of `deliver/2` is inconsistent as I believe its a convention to append a ! (bang) to the routines that'll raise an exception. In other words, do you its sane to change the current `deliver/2` to `deliver!/2` and add another `deliver/2` that'll return `{:ok,  %{status_code: status, headers: headers, body: response}}` or `{:error, :api_error}.`

I understand that'll require change on the Bamboo codebase as well but what do you think? 

P/S: I can help in submitting the PR should you agree to make the change.

**Comment by pablo-co** [comment]
I actually agree with you, it is indeed a convention to add a bang for functions that raise exceptions. You should raise this concern in the [bamboo repo](https://github.com/thoughtbot/bamboo) since they decide what the interface for adapters is.

**Comment by pablo-co** [comment]
Will reopen this issue when bamboo addresses this!
