### ISSUE TITLE
Remove Poison Dependency

### ISSUE THREAD

**Issue by BenMorganIO** [pablo-co/bamboo_postmark#21]
Bamboo comes with `config :bamboo, :json_library, MyJsonLibrary`. I'm wondering if it's possible to use that here instead of using poison.

**Comment by pablo-co** [comment]
Right now it's not posible to do that, but it sounds like something that may be useful. I would like to know a little more about your specific use case; Do you want to change the JSON library in order to avoid Poison as a dependency or is there some other reason I might be missing?

**Comment by BenMorganIO** [comment]
Well, when I run a `mix deps.get` I end up with two JSON libraries. One is Poison and the other is Jason. My goal here is to consolidate the application to a single JSON library rather than see several get installed.

**Comment by pablo-co** [comment]
Will work on adding this enhancement on the weekend, will keep you posted!

**Comment by pablo-co** [comment]
I just released version 0.5.0 with this feature.
