### ISSUE TITLE
Required callback supports_attachments? not implemented from Bamboo.Adapter

### ISSUE THREAD

**Issue by sparta-developers** [pablo-co/bamboo_postmark#27]
Bamboo just released a new version, and there are some changes to `Bamboo.Adapter` that cause compilation warnings. Specifically, a new callback was added:

```elixir
@callback supports_attachments? :: boolean
```

The mailer implements this:

```elixir
defp validate_attachment_support(%{attachments: []} = email, _adapter), do: email

defp validate_attachment_support(email, adapter) do
  if function_exported?(adapter, :supports_attachments?, 0) && adapter.supports_attachments? do
    email
  else
    raise "the #{adapter} does not support attachments yet."
  end
end
```

I don't think that this effects our codebase, because we don't send attachments as a part of our mailer. I thought you might want to know about this, though, to either pin bamboo to `~> 1.2.0` or implement the callback.

/cc @sax

**Comment by pablo-co** [comment]
Thanks for reporting this issue! Will look into it in the weekend! Will keep you posted.
