### ISSUE TITLE
Support for template alias

### ISSUE THREAD

**Issue by mustela** [pablo-co/bamboo_postmark#28]
Hello there! 

Is there already any plan to support TemplateAlias para instead of templateID? 

Thanks!

**Comment by pablo-co** [comment]
It looks like something we should support. I'll look into this during the weekend.

**Comment by mustela** [comment]
Hey @pablo-co have you started to work on it? If not, happy to work on it, if you give me some guidance. I guess I could duplicate this method https://github.com/pablo-co/bamboo_postmark/blob/master/lib/bamboo/postmark_helper.ex#L34, and replace `template_id` with a map like `{template_alias: xx}`. 

Let me know if you have any thoughts. Thanks!

**Comment by pablo-co** [comment]
I've been having some really busy weeks. Let me think this through as I want to make sure whatever we choose to implement is the right interface to expose.

**Comment by mustela** [comment]
No problem! Happy to work on it if you want to.

**Comment by mustela** [comment]
Hey @pablo-co is there any plan for this? I can try if this is not in your plans.

**Comment by pablo-co** [comment]
@mustela feel free to do so! I've been unable to find the time to do so. 👍
