### ISSUE TITLE
Postmark disabling TLSv1.0 access

### ISSUE THREAD

**Issue by nickagliano-st** [pablo-co/bamboo_postmark#38]
Will this Postmark Adapter still work with the upcoming TLS configuration changes coming down from Postmark?

Announced by Postmark [here](https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required).

> ### What’s changing
> (1) Disable TLSv1.0 access, 
> (2) Disable all RC4 and low-strength ciphers
> (3) Add HSTS headers

It looks like the postmark-rails changelog mentions they made a fix, see [here](https://github.com/wildbit/postmark-rails/blob/master/CHANGELOG.rdoc). Will something similar need to be done?

**Comment by pablo-co** [comment]
I'll look into this! 👍

**Comment by kylenathan** [comment]
Postmark are running a blackout test today it seems from 11am ET to 11pm ET.
https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required

We only just saw this and have had a huge product launch today (ahhh). 

If the lib uses TLS 1.0 this could be a big issue for us. Totally understand that you may be busy @pablo-co  and really appreciative for all your work. If there is any way you could quickly let us know if we need to worry about this that would be very helpful, but again I completely understand if not.

**Comment by kylenathan** [comment]
From looking at the code I guess it depends on the version of Hackney?

**Comment by pablo-co** [comment]
I'm unable to verify the version requirements for hackney at the moment. This can be tested against `api-ssl-temp.postmarkapp.com`. I'm happy to merge a PR if any of you can verify the new minimum hackney version needed to work against that endpoint. 🙏

**Comment by kylenathan** [comment]
Hey @pablo-co, thanks for responding so quickly. We tested the version of hackney used by our application against the temp endpoint and it was fine so all good in the end. I will check if the current min version in this lib meets the TLS 1.2 requirement and let you know.
